//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Spacer.rc
//
#define ID_ICON_COLOR                   2
#define ID_INFO                         3
#define ID                              3
#define IDC_CLIPBOARD                   3
#define IDD_ABOUTBOX                    100
#define CG_ID_VIEW_CMATERIALDIALOGBAR   103
#define CG_ID_VIEW_INFOBAR_MATERIALS    105
#define DIALOG_CRASH                    123
#define IDR_MAINFRAME                   128
#define IDR_PPFTYPE                     129
#define IDB_VOB_TOOLBAR                 130
#define IDR_POPUPS                      132
#define IDR_BROWSE_POPUPS               133
#define IDR_OBJECTS                     134
#define IDR_OBJECTACTIONS               136
#define IDR_MATERIALACTIONS             137
#define IDD_INFO_EMPTY                  137
#define IDD_BROWSE_EMPTY                138
#define DIALOG_FILENOTFOUND             140
#define IDR_TOOLBAR_EMPTY1              143
#define DIALOG_OUTOFMEM                 143
#define IDD_SETTINGS_VIEW               144
#define IDD_BROWSE_VOBS                 145
#define IDD_BROWSE_MATS                 146
#define IDD_INFO_ITEM                   147
#define DIALOG_EXCEPTION                147
#define DIALOG_ASSERT                   148
#define IDD_INFO_LIGHT                  150
#define IDD_INFO_SOUNDS                 151
#define IDD_INFO_MATERIAL               152
#define IDD_INFO_SPECIAL                153
#define IDD_SETTINGS_SCRIPTS            155
#define IDD_WORKING_DLG                 156
#define IDD_WORK_INFO_DLG               156
#define IDD_COMPILE                     157
#define IDD_COMPILE_WORLD_DLG           157
#define IDD_SETTINGS_GENERAL            159
#define IDD_INFO_MATERIALS              160
#define IDD_INFO_ITEMS                  161
#define IDD_INFO_NSCS                   163
#define IDD_INFO_SPECIALS               164
#define IDD_LIST_MATS                   165
#define IDD_LIST_VOBS                   166
#define IDD_DEF_FILTERS                 168
#define IDD_INPUT_DLG                   170
#define IDD_PROPERTY_DLG                173
#define IDD_MESSAGE_DLG                 174
#define IDD_COMPILE_LIGHT_DLG           175
#define IDD_MATFILTERSAV                178
#define IDD_MAT_CONCHECK                179
#define IDD_INFO_SCRIPTS                181
#define __OLD_OLD_IDD_INFO_SCRIPTS      181
#define IDD_LIST_OUS                    182
#define IDR_SCRIPTACTIONS               186
#define IDD_DIAGRAM_VIEPORT             187
#define IDD_DIAGRAM_VIEWPORT            187
#define IDR_CSMENU                      191
#define IDD_DIAGRAMVIEW                 192
#define IDD_CS_SEQUENCER                192
#define IDD_WORKING_INFO                193
#define IDD_WORK_PROGRESS_DLG           193
#define IDD_INFO_DYNDLG                 194
#define IDD_INFO_EVENTS                 195
#define IDD_INFO_VOBS                   196
#define __OLD_OLD_IDD_INFO_VOBS         196
#define IDD_SETTINGS_CS                 197
#define IDD_INFO_VOBSPLUS               198
#define __OLD_OLD_IDD_INFO_VOBSPLUS     198
#define IDD_INFO_CAMERA                 199
#define IDD_MSG_DYNDLG                  200
#define IDD_INFO_LOGICAL                201
#define IDD_INFO_VERTEX                 202
#define IDD_MAT_EDIT                    203
#define IDD_MAKRODIALOG                 219
#define IDD_DYNAMIC_DIALOG              221
#define IDD_DIALOG1                     224
#define IDD_INPUT_DLG_POSITION          225
#define IDD_CONSOLE_DLG                 226
#define IDD_DIALOG2                     227
#define IDD_DIALOG3                     228
#define DIALOG_BOUNDS                   229
#define IDD_INFORMATION_DIALOG          230
#define IDD_TEXTINFO_DLG                230
#define IDD_DAYTIME_DLG                 234
#define IDD_NEW_MATERIALS_DIALOG        235
#define IDD_VOB_PRESET_DLG              236
#define IDR_ICONS_VOBLIST               243
#define IDR_ICONS_VOBPROPS              244
#define IDD_HTML_HELP                   245
#define IDD_VOB_PROPERTY_DLG            246
#define IDD_VOB_LIST_DLG                247
#define IDD_OBJECT_CREATION_PAGE        249
#define IDD_OBJECT_DLG                  250
#define IDD_OBJECT_MODIFY_PAGE          251
#define IDD_INFOHELP_DLG                256
#define IDD_HELP_DLG                    256
#define IDD_OBJECT_MANIPULATE_PAGE      257
#define IDD_OBJECT_SRIPTED_DLG          258
#define IDD_INFO_DEFAULT                259
#define IDC_CURSOR1                     259
#define IDD_WORLD_ANALYSE               260
#define IDR_PRESET_EXPORT               266
#define IDD_BBOX_DEFINE                 273
#define IDD_VOB_CONTAINER               274
#define IDD_MANIPULATE_SOUNDS           277
#define IDR_NULLMENU			278
#define IDC_QUIT                        1003
#define IDC_VIEW_Y                      1004
#define IDC_VIEW_X                      1005
#define IDC_MOVE_SPEED                  1007
#define IDC_MOVE_FARCLIP                1008
#define IDC_MATLIST                     1008
#define IDC_COMBO1                      1009
#define IDC_LIGHT_DYN_QUALITY           1009
#define IDC_CAM_ALIGN                   1009
#define IDC_SC_SELECTOR                 1009
#define IDC_DYENUM                      1009
#define IDC_VISUALNAME                  1009
#define IDC_SELECT_FILTER               1009
#define IDC_VIDEO_DEVICE                1009
#define IDC_MAT_FILTER_EDIT             1010
#define IDC_ALPHA_BLEND                 1010
#define IDC_CAM_ALIGN2                  1010
#define ID_CANCEL                       1010
#define IDC_VIDEO_RESOLUTION            1010
#define IDC_BROWSE                      1011
#define IDC_ALPHA_BLEND2                1011
#define IDC_PRESET_CLASS                1012
#define IDC_ERRORTEXT                   1023
#define IDC_PATH                        1024
#define IDC_DO_SELECT                   1025
#define IDC_LOG                         1031
#define IDC_FILTER_BUTTON               1032
#define IDC_VOBLIST                     1033
#define IDC_NAME                        1034
#define IDC_CLASSSELECTOR               1034
#define IDC_CD_DYN                      1035
#define IDC_CLASSSELECTOR_NC            1035
#define IDC_CD_STAT                     1036
#define IDC_STATICVOB                   1037
#define IDC_SEL_CD_DYN                  1038
#define IDC_FILENOTFOUND                1038
#define IDC_FILTERLIST                  1039
#define IDC_TEX_PREVIEW                 1040
#define IDC_SEL_CD_STAT2                1040
#define IDC_SEL_CD_STAT                 1040
#define IDC_MAT_NAME                    1041
#define IDC_SEL_STATICVOB2              1041
#define IDC_SEL_STATICVOB               1041
#define IDC_BUTTON1                     1042
#define IDC_SELECT_TEXTURE              1042
#define IDC_ADD                         1042
#define IDC_PRESET_TO_CURRENT           1042
#define IDC_SEL_NAME                    1042
#define IDC_SELALL                      1042
#define IDC_SC_COMPILE                  1042
#define IDC_PART_NEW                    1042
#define IDC_TIMEDEC                     1042
#define IDC_DELETE_OU                   1042
#define IDC_DYN_APPLY                   1042
#define IDC_VISUALBUTTON                1042
#define IDC_PRINT_TO_FILE               1042
#define IDC_MAT_CANCEL                  1042
#define IDC_CAM_PLAY                    1042
#define IDC_RENAME                      1042
#define ID_RETRY                        1042
#define IDC_APPLY_TO_VOB                1042
#define IDC_CHANGES                     1042
#define IDC_ACTION_RIGHT                1042
#define IDC_INSERT_OBJECT               1042
#define IDC_APPLY                       1042
#define IDC_WORLD_STORE_VOBSTATES       1042
#define IDC_GOTO_VOB                    1042
#define IDC_EXPORT_PRESETS              1042
#define IDC_VC_MODUS                    1042
#define IDC_BUTTON2                     1043
#define IDC_REMOVE_TEXTURE              1043
#define IDC_REMOVE                      1043
#define IDC_PRESET_NEW                  1043
#define IDC_REJECT                      1043
#define IDC_PART_EDIT                   1043
#define IDC_TIMEINC                     1043
#define IDC_DYN_INSERT                  1043
#define IDC_DELETE_OU2                  1043
#define IDC_NEW_OU                      1043
#define IDC_CREATEKEY                   1043
#define IDC_CAM_STOP                    1043
#define IDC_DELETE                      1043
#define IDC_MEMERROR                    1043
#define IDC_VOB_GOTO                    1043
#define IDC_CORE_CHANGES                1043
#define IDC_ACTION_LEFT                 1043
#define IDC_WORLD_RESTORE_VOBSTATES     1043
#define IDC_FIX                         1043
#define IDC_RESET                       1043
#define IDC_DEL_PRESET                  1043
#define IDC_TEST                        1043
#define IDC_VC_ACTIONS                  1043
#define IDC_TEX_NAME                    1044
#define IDC_PRESET_FROM_CURRENT         1044
#define IDC_REJECTALL                   1044
#define IDC_TIMESCROLL_L                1044
#define IDC_PRESET_TO_CURRENT_T         1044
#define IDC_MEMPHYS                     1044
#define IDC_INSERT_TO_WORLD             1044
#define IDC_ACTION_CENTER               1044
#define IDC_SAVE                        1044
#define IDC_PRESET_REMOVE               1045
#define IDC_TIMESCROLL_R                1045
#define IDC_MEMSWAP                     1045
#define IDC_CAM_KF_GOTO                 1045
#define IDC_APPLY_CHANGES               1045
#define IDC_TEX_INFO                    1046
#define IDC_EDIT_CURRENT                1046
#define IDC_PRESET_FROM_CURRENT_T       1046
#define IDC_MEMLOAD                     1046
#define IDC_PRESET_REAPPLY              1046
#define IDC_SYNCBLOCK_DEL               1046
#define IDC_MAT_GROUP                   1047
#define IDC_EDIT_SELECTED               1047
#define IDC_PRESET_RELOAD               1047
#define IDC_PRESET_REMOVE_T             1047
#define IDC_MEMPHYSFREE                 1047
#define IDC_SYNCBLOCK_INS               1047
#define IDC_PRESET_RELOAD_T             1048
#define IDC_MEMSWAPFREE                 1048
#define IDC_CREATE_PRESET               1048
#define IDC_SYNCBLOCK_ADD               1048
#define IDC_MAT_EDIT                    1049
#define IDC_MAT_SMOOTH                  1050
#define IDC_MEMFREE                     1050
#define IDC_MAT_SMOOTH_DEGREES          1051
#define IDC_MEMREQUIRED                 1051
#define IDC_ANI_FRAME_FPS               1052
#define IDC_MEMDIFF                     1052
#define IDC_SET_MAPPING                 1053
#define IDC_ICONINFO                    1053
#define IDC_ANI_MAPPING                 1054
#define IDC_EXCEPTIONCAPTION            1054
#define IDC_ANI_X                       1055
#define IDC_CLOSE                       1055
#define IDC_ANI_Y                       1056
#define IDC_MAT_COLORBTN                1057
#define IDC_EXCEPTIONTEXT               1057
#define IDC_MAT_COLOR                   1058
#define IDC_MAT_AVCOLORBTN              1058
#define IDC_INTREGLIST                  1058
#define IDC_MAT_OPACITY                 1059
#define IDC_SEGREGLIST                  1059
#define IDC_VIEW                        1060
#define IDC_MAP_X                       1060
#define IDC_PTRREGLIST                  1060
#define IDC_MAP_Y                       1061
#define IDC_MAT_NEW                     1062
#define IDC_CALLSTACK                   1062
#define IDC_MAT_FILTER                  1063
#define IDC_ASSERTCAPTION               1063
#define IDC_ANI_X_TEXT                  1064
#define IDC_ANI_Y_TEXT                  1065
#define IDC_ASSERTION                   1065
#define IDC_ANI_FRAME_TEXT1             1066
#define IDC_FILE                        1066
#define IDC_ANI_FRAME_TEXT2             1067
#define IDC_REASON                      1067
#define IDC_ANI_GROUP                   1068
#define IDC_REASON_TEXT                 1068
#define IDC_MAT_NEW_WO                  1069
#define IDC_NEW                         1070
#define IDC_MAT_MULTINEW                1070
#define IDC_COMPILE                     1071
#define IDC_MAT_UPDATE                  1071
#define IDC_ERRORCAPTION                1071
#define IDC_QUICKCOMPILE                1072
#define IDC_DETECT_LEAKS                1073
#define IDC_DEBUG                       1073
#define IDC_STARTUP_LOAD                1074
#define IDC_STARTUP_PARSE               1075
#define IDC_FILTER                      1076
#define IDC_REFRESH                     1077
#define IDC_USE_GRID                    1078
#define IDC_MOVEGRID                    1079
#define IDC_ROTGRID                     1080
#define IDC_WAYPOINTS                   1080
#define IDC_DECALS                      1081
#define IDC_WAYPOINTS2                  1081
#define IDC_CAMERA                      1082
#define IDC_PARTICLES                   1083
#define IDC_START                       1084
#define IDC_USE_TEX_GRID                1084
#define IDC_SPOTS                       1085
#define IDC_TEX_MOVEGRID                1085
#define IDC_LIST                        1086
#define IDC_TEX_ROTGRID                 1086
#define IDC_VOB_LIST                    1087
#define IDC_LIST_EX                     1087
#define IDC_MARKER                      1087
#define IDC_SPOTS2                      1087
#define IDC_DECAL                       1087
#define IDC_EDIT                        1096
#define IDC_EDIT_Y                      1097
#define IDC_EDIT_Z                      1098
#define IDC_STATIC_LIGHT                1099
#define IDC_AT_X                        1099
#define IDC_DYNAMIC_LIGHT               1100
#define IDC_AT_Y                        1100
#define IDC_COLOR_LIST                  1101
#define IDC_AT_Z                        1101
#define IDC_RANGE_LIST                  1102
#define IDC_COLOR_ADD                   1103
#define IDC_COLOR_DEL                   1104
#define IDC_COLOR_SMOOTH                1105
#define IDC_RANGE_ADD                   1106
#define IDC_COLOR_CHPS                  1107
#define IDC_RANGE_DEL                   1108
#define IDC_PRESET_LIST                 1109
#define IDC_ANI_FPS                     1110
#define IDC_COLOR_UP                    1110
#define IDC_COLOR_DOWN                  1111
#define IDC_RANGE_SMOOTH                1112
#define IDC_INSTANCENAME                1112
#define IDC_RANGE_CHPS                  1113
#define IDC_INSTANCE_NAME               1113
#define IDC_SEL_INSTANCENAME            1113
#define IDC_2SIDED                      1114
#define IDC_SEL_INSTANCENAME2           1114
#define IDC_PROPERTY_GROUP              1117
#define IDC_PROP_GROUP                  1118
#define IDC_SEL_PROP_GROUP              1119
#define IDC_MESSAGE                     1121
#define IDC_SHADOWS                     1123
#define IDC_INDOOR                      1125
#define IDC_OUTDOOR                     1126
#define IDC_WORLD                       1127
#define IDC_OPTIONS                     1128
#define IDC_LIGHT1                      1129
#define IDC_LIGHT2                      1130
#define IDC_LIGHT3                      1131
#define IDC_LIGHT4                      1132
#define IDC_CAMLIGHT                    1134
#define IDC_LIST1                       1135
#define IDC_CHECKJUMP                   1136
#define IDC_CHECKFREE                   1137
#define IDC_CHECKCLIMB                  1138
#define IDC_CHECKSWIM                   1139
#define IDC_CHECKDIVE                   1140
#define IDC_STATICWP                    1141
#define IDC_EDITORMODE                  1142
#define IDC_TOVOB                       1143
#define IDC_TOVOB_LABEL                 1144
#define IDC_DECAL_FROM_CURRENT          1145
#define IDC_DECAL_TO_CURRENT            1146
#define IDC_SC_EDIT                     1147
#define IDC_STATICMARK                  1149
#define IDC_EDITX                       1150
#define IDC_EDITZ                       1151
#define IDC_EDITY                       1152
#define IDC_STATICMX                    1153
#define IDC_STATICMY                    1154
#define IDC_POLYCHECK                   1154
#define IDC_STATICMZ                    1155
#define IDC_OU_FILTER                   1164
#define IDC_OU_REFRESH                  1165
#define IDC_OU_LIST                     1166
#define IDC_OU_LANGUAGE                 1167
#define IDC_CHECKMAP                    1168
#define IDC_TRACKTREE                   1169
#define IDC_TIMESCROLLBAR               1173
#define IDC_OUTEXT                      1177
#define IDC_VIEWENABELD                 1178
#define IDC_WORKPROGRESS                1179
#define IDC_PROPTREE                    1180
#define IDC_DYBOOL                      1181
#define IDC_DYVALUE                     1182
#define IDC_DYSTRING                    1183
#define IDC_DYVECTOR1                   1184
#define IDC_DYVECTOR2                   1185
#define IDC_DYVECTOR3                   1186
#define IDC_DYRAW                       1192
#define IDC_CLASSNAME                   1193
#define IDC_VOBNAME                     1194
#define IDC_KF_EDIT                     1197
#define IDC_KFC_AFTER                   1198
#define IDC_KFC_BEFORE                  1199
#define IDC_KF_DEC                      1203
#define IDC_KF_INC                      1204
#define IDC_EDITBBOX                    1205
#define IDC_DELETEKEY                   1206
#define IDC_EDITCOLOR                   1212
#define IDC_TESTEVENT                   1213
#define IDC_SENDEVENT                   1214
#define IDC_EVENTRESTORE                1215
#define IDC_EVTRIGER                    1216
#define IDC_EVUNTRIGER                  1217
#define IDC_KFC_OVERWRITE               1218
#define IDC_BUTTON3                     1219
#define IDC_HELP_BUTTON                 1219
#define IDC_SHOW_PROP                   1219
#define IDC_EVENT_SEND                  1219
#define IDC_ASSIGN_QUICKSLOT            1219
#define IDC_OU_START                    1219
#define IDC_ANALYSE                     1219
#define IDC_LOAD                        1219
#define IDC_ACTION_DEFINE               1219
#define IDC_PROP_LIST                   1220
#define IDC_ROLE_DEL                    1220
#define IDC_STATIC_VISUAL               1221
#define IDC_LOOPABLE                    1223
#define IDC_EDIT_SYNCBLOCK              1224
#define IDC_SPLINE_CAM                  1225
#define IDC_TIME_VALUE                  1225
#define IDC_SPLINE_TARGET               1226
#define IDC_SPLINE                      1227
#define IDC_LODCOLLAPS                  1229
#define IDC_LOGICNEW_OLD                1235
#define IDC_CHECK_DELETE                1236
#define IDC_SPEED_SLIDER                1238
#define IDC_MAT_EDITBOX                 1239
#define IDC_PROGRESSBAR                 1240
#define IDC_REF_CAM                     1241
#define IDC_REF_TARGET                  1242
#define IDC_TREE1                       1245
#define IDC_DATALIST                    1249
#define IDC_DATAGRID1                   1251
#define IDC_MSHFLEXGRID1                1252
#define IDC_EDIT_X                      1253
#define IDC_INPUT                       1254
#define IDC_OUTPUT                      1255
#define ID_CLOSEDLG                     1257
#define IDC_AUTOCOMPLETE                1258
#define IDC_ENABLE_PRESETS              1259
#define IDC_CAMPLAY_DURATION            1260
#define IDC_CAM_PLAY_DURATION           1260
#define IDC_LEVELNAME                   1261
#define IDC_CONTENTS                    1262
#define IDC_SND_PLAYNAME                1263
#define IDC_SND_PLAY                    1265
#define IDC_TEX_MOVEMENT                1267
#define IDC_TEX_MOVE_SPIN               1272
#define IDC_CS_START                    1274
#define IDC_CS_STOP                     1275
#define IDC_SRCVERSION                  1275
#define IDC_CS_STEP                     1275
#define IDC_CS_REPEAT                   1276
#define IDC_CS_INFO                     1277
#define IDC_CS_INFORMATION              1277
#define IDC_COLORVIEW                   1278
#define IDC_STRING_FILE                 1279
#define IDC_EFFECT_DERIVED              1280
#define IDC_EDIT_BBOX                   1283
#define IDC_HOLD_TIME                   1288
#define IDC_DAYTIME                     1289
#define IDC_NEW_FILTER                  1293
#define IDC_SEL_NONE                    1294
#define IDC_NEW_FILTER2                 1294
#define IDC_DEL_FILTER                  1294
#define IDC_SEL_FILTER                  1295
#define IDC_SEL_NEW_FILTER              1296
#define IDC_PRESET_ASSIGN_TO_CURRENT    1296
#define IDC_PRESET_UPDATE_FROM_CURRENT  1297
#define IDC_TEMPLATE_LIST               1298
#define IDC_TEXT                        1299
#define IDC_CLASS_LIST                  1300
#define IDC_PROGRESS_FOUND              1301
#define IDC_SORTED                      1302
#define IDC_VOB_PRESET_NAME             1313
#define IDC_VOBINFO                     1317
#define IDC_EDIT_AREA                   1319
#define IDC_DYVALUE_SPIN                1321
#define IDC_OBJ_TAB                     1323
#define IDC_OBJ_ACTION                  1324
#define IDC_PRESETLIST                  1325
#define IDC_CLASSTREE                   1326
#define IDC_HELPTEXT                    1327
#define IDC_MODE_INFO                   1328
#define IDC_INFORMATION                 1331
#define IDC_EVENT_LIST                  1333
#define IDC_VIEWPORT_PLACEHOLDER        1337
#define IDC_COLLECT                     1340
#define IDC_LIST_SOURCES                1341
#define IDC_LIST_TARGETS                1342
#define IDC_OBJECT_TYPE                 1344
#define IDC_OBJECT_NAME                 1345
#define IDC_INSTANCE_LIST               1346
#define IDC_SOURCEVOB                   1347
#define IDC_QUICKSLOT                   1348
#define IDC_FILTER_FIX                  1349
#define IDC_FILTER_COMMENT              1350
#define IDC_COLOR_ALPHA                 1352
#define IDC_INFO                        1355
#define IDC_STEP                        1356
#define IDC_INS_CURRENT_POS             1357
#define IDC_INSERT_CAMERA               1358
#define IDC_REMOVE_PRESET               1359
#define IDC_PROGRESS                    1362
#define IDC_SIMULATE                    1363
#define IDC_CHECK1                      1364
#define IDC_SAVE_INTERATIVE             1364
#define IDC_REPLACE_WITH_ZEN            1364
#define IDC_REGION                      1364
#define IDC_GRID                        1364
#define IDC_LIGHT_SHOWRANGES            1364
#define IDC_FASTUPDATE                  1364
#define IDC_EDIT1                       1365
#define IDC_SEARCH                      1365
#define IDC_STATE                       1365
#define IDC_REGION_VALUE                1365
#define IDC_DZ                          1365
#define IDC_MULT_VOLUMES                1365
#define IDC_STORE_PROGRESS              1366
#define IDC_DX                          1366
#define IDC_MULT_RANGES                 1366
#define IDC_ROLE_ADD                    1367
#define IDC_DY                          1367
#define IDC_CHECK2                      1368
#define IDC_CORRECT_TRAFO               1368
#define IDC_GOLDMASTER                  1368
#define IDC_LIGHT_DYNAMIC_COMPILE       1368
#define IDC_VIEWPORT_SCROLLBAR          1375
#define IDC_ACTION_TYPE                 1384
#define IDC_BUTTON4                     1387
#define IDC_TIDY_VOBS                   1387
#define ID_ADDTRACK_00                  16000
#define ID_ADDTRACK_01                  16001
#define ID_ADDTRACK_02                  16002
#define ID_ADDTRACK_03                  16003
#define ID_ADDTRACK_04                  16004
#define ID_ADDTRACK_05                  16005
#define ID_ADDTRACK_06                  16006
#define ID_ADDTRACK_07                  16007
#define ID_ADDTRACK_08                  16008
#define ID_ADDTRACK_09                  16009
#define ID_ADDTRACK_0A                  16010
#define ID_ADDTRACK_0B                  16011
#define ID_ADDTRACK_0C                  16012
#define ID_ADDTRACK_0D                  16013
#define ID_ADDTRACK_0E                  16014
#define ID_ADDTRACK_0F                  16015
#define ID_ADDTRACK_10                  16016
#define ID_ADDTRACK_11                  16017
#define ID_ADDTRACK_12                  16018
#define ID_ADDTRACK_13                  16019
#define ID_ADDTRACK_14                  16020
#define ID_ADDTRACK_15                  16021
#define ID_ADDTRACK_16                  16022
#define ID_ADDTRACK_17                  16023
#define ID_VIEWMATERIAL_MOVE            32773
#define ID_VIEWMATERIAL_ROTATE          32774
#define ID_VIEWMATERIAL_SCALE           32775
#define ID_OBJ_MOB                      32784
#define ID_OBJ_NSC                      32785
#define ID_OBJ_SOUND                    32786
#define ID_OBJ_LIGHT                    32787
#define ID_OBJ_SPECIAL                  32788
#define ID_BUTTON32790                  32790
#define ID_BUTTON32791                  32791
#define ID_VOB_MOVE                     32793
#define ID_BUTTON32794                  32794
#define ID_OBJ_ITEM                     32797
#define ID_OBJ_TEXTURE                  32798
#define ID_SETTINGS_VIEW                32799
#define ID_WORLD_COMPILE                32800
#define ID_WORLD_COMPILELIGHT           32801
#define ID_SETTINGS_FULLSCREEN          32802
#define ID_VOB_CONTROL                  32803
#define ID_VOB_TAKEOVER                 32804
#define ID_VOB_REMOVE                   32805
#define ID_VOB_PHYSICS                  32806
#define ID_VOB_COLLDET                  32807
#define ID_POLY_INSERT                  32808
#define ID_POLY_APPLY                   32808
#define ID_POLY_PICKMATERIAL            32809
#define ID_POLY_NEWMAT                  32810
#define ID_POLY_DELMATERIAL             32811
#define ID_SETTINGS_SCRIPT              32812
#define ID_WORLD_PARSESCRIPT            32813
#define ID_WORLD_LOADSCRIPT             32814
#define ID_WORLD_DIFSCRIPT              32815
#define ID_VOB_INSERT                   32816
#define ID_POLY_INSERTMAP               32817
#define ID_POLY_APPLYM                  32817
#define ID_VOB_PROPERTIES               32821
#define ID_BROWSEVOBS_GOTO              32823
#define ID_BROWSEVOBS_ACTIVATE          32824
#define ID_BROWSEVOBS_REMOVE            32826
#define ID_BROWSEVOBS_ACTGOTO           32827
#define ID_SETTINGS_GENERAL             32828
#define ID_VOB_COLLISION_DETECTION      32829
#define ID_BUTTON32831                  32831
#define ID_WAY_CREATE                   32831
#define ID_VIEW_FOGGING                 32833
#define ID_SAVE_SETTINGS                32835
#define ID_LOAD_SETTINGS                32836
#define ID_VIEW_HELPERVOBS              32837
#define ID_POLY_TOGGLE_SEL              32838
#define ID_VIEW_AUTOMAP                 32839
#define ID_SAVE_MATFILTER               32840
#define ID_LOAD_MATFILTER               32841
#define ID_VOB_SAVE_TREE                32842
#define ID_VOB_INSERT_TREE              32843
#define ID_VOB_INSERTMESH_ITEM          32844
#define ID_VOB_INSERTMESH_MOB           32845
#define ID_VOB_INSERTMESH_VOB           32846
#define ID_FILE_MERGE                   32847
#define IDC_SAVE_SETTINGS               32849
#define ID_VIEW_WIRE                    32850
#define ID_FILE_REOPEN                  32851
#define ID_FILE_REOPEN2                 32852
#define ID_OBJ_SCRIPT                   32853
#define ID_EXTRACTTEXT                  32854
#define ID_IMPORTTEXT                   32855
#define ID_VIEW_NORMAL                  32858
#define ID_CUTSCENESEQ                  32859
#define ID_CSSAVE                       32863
#define ID_ADDTRACK_ANI                 32864
#define ID_CSOPEN                       32865
#define ID_DOAI                         32866
#define ID_ADDTRACKSND                  32867
#define ID_ADDTRACKTURN                 32868
#define ID_CSSAVE_AS                    32869
#define ID_CSNEW                        32870
#define ID_ADDROLE                      32871
#define ID_OBJ_EVENT                    32872
#define ID_FILE_OPENMAKEFILE            32873
#define ID_OBJ_PROPS                    32875
#define ID_POLY_DESELECT                32876
#define ID_POLY_APPLY_DES               32877
#define ID_REMOVETRACK                  32879
#define ID_REMOVEBLOCK                  32880
#define ID_CONVERT1                     32881
#define ID_CONVERT2                     32882
#define ID_ADDSYNCBLOCK                 32883
#define ID_REMOVEROLE                   32884
#define ID_OBJ_VOBS                     32885
#define ID_INSERTSYNCBLOCK              32886
#define ID_CSPROPS                      32887
#define ID_OBJ_ZONE                     32888
#define ID_PRESETSAVE                   32889
#define ID_ADDGENTRACK                  32890
#define ID_OBJ_CAMERAS                  32893
#define ID_CS_INTEGRATE                 32895
#define ID_POLY_PLANAR                  32896
#define ID_OBJ_LOGICAL                  32897
#define ID_REMOVESYNC                   32898
#define ID_OBJ_VERTEX                   32899
#define ID_ROLEPROPS                    32900
#define ID_CS_DECLARE_PC                32901
#define ID_TOOLS_MACROS                 32902
#define ID_VIEW_FULLSCREEN              32903
#define ID_VIEW_CONSOLE                 32904
#define ID_TOOLS_GOTOVOB                32906
#define ID_TOOLS_GOTOPOSITION           32907
#define ID_TOOLS_GOTOSTARTPOINT         32908
#define ID_TOOLS_GOTOORIGIN             32928
#define ID_TOOLS_SPECIAL_SAVETMPDOC     32929
#define ID_TOOLS_SPECIAL_LOADTMPDOC     32930
#define ID_FILE_OPENMESH                32931
#define ID_FILE_MERGEMESH               32932
#define ID_CUTSCENE_UPDATEOU            32934
#define ID_BUTTON32935                  32935
#define ID_VIEW_SIZEDHELPERS            32936
#define ID_FILE_SAVE_ZEN                32938
#define ID_FILE_SAVE_MESH               32939
#define ID_VIEWVOB_COPY                 32941
#define ID_VIEWVOB_PASTE                32942
#define ID_TOOLS_INFORMATIONS           32943
#define ID_VIEWVOB_PLAY                 32944
#define ID_KEY_POPUP                    32945
#define ID_VIEW_SOUND_ALLON             32950
#define ID_VIEW_SOUND_ALLOFF            32951
#define ID_VIEWVOB_GOTO_5METERS         32955
#define ID_VIEWVOB_GOTO_2METERS         32956
#define ID_VIEWVOB_GOTO_1METER          32957
#define ID_VIEWVOB_GOTO_HALFMETER       32958
#define ID_SHORTCUT_1_DEF               32959
#define ID_SHORTCUT_2_DEF               32960
#define ID_SHORTCUT_3_DEF               32961
#define ID_SHORTCUT_1                   32962
#define ID_SHORTCUT_2                   32963
#define ID_SHORTCUT_3                   32964
#define ID_SHORTCUT_4_DEF               -32571
#define ID_SHORTCUT_4                   32966
#define ID_VIEWVOB_VOB_LETFALLDOWN      32971
#define ID_QUICK_OPEN                   32972
#define ID_QUICK_SAVE                   32973
#define ID_VIEW_DAYTIME                 32974
#define ID_VIEWVOB_INSERTFROMPRESET     32976
#define ID_VIEW_PRESETLIB               32978
#define ID_VIEWVOB_VOB_CREATEPRESET     32979
#define ID_ICON_FOLDER                  32980
#define ID_ICON_VOB                     32981
#define ID_ICON_VOB_NEW                 32982
#define ID_ICON_LEVEL_COMPONENT         32983
#define ID_ICON_UNKNOWN                 32984
#define ID_ICON_ROOT                    32985
#define ID_HELP_HELP                    32986
#define ID_VIEW_TOGGLESOUND             32990
#define ID_VIEW_WAYNET                  32991
#define ID_ICON_CHUNKEND                32992
#define ID_ICON_BOOL                    32993
#define ID_ICON_STRING                  32994
#define ID_ICON_INT                     32995
#define ID_ICON_FLOAT                   32996
#define ID_ICON_ENUM                    32997
#define ID_ICON_                        32998
#define ID_BUTTON33001                  33001
#define ID_ICON_CLASS                   33003
#define ID_BUTTON33004                  33004
#define ID_WINDOWS_ANBINDEN             33005
#define ID_WINDOWS_ALIGNRIGHT           33006
#define ID_WINDOWS_INFORMATIONWINDOW    33007
#define ID_PRESETLIST_UPDATEALLOBJECTS  33010
#define ID_PRESETLIST_UPDATESELECTEDOBJECT 33011
#define ID_PRESETLIST_DELETEPRESET      33012
#define ID_VIEWVOB_VOB_INITEVENTS       33013
#define ID_PRESETLIST_CONVERTSELECTEDOBJECT 33014
#define ID_KEY_CTRL_1                   33015
#define ID_VIEWEDIT_TOGGLEVOBBOXES      33016
#define ID_OBJ_CUTSCENES                33017
#define ID_VIEWEDIT_TOGGLEBILINEARFILTERING 33018
#define ID_WORLD_ANALYSE                33019
#define ID_VOB_INSERT_BY_KEY            -32516
#define ID_EDIT_ADDROLE_MAIN            33023
#define ID_EDIT_ADDSPECIALROLE_THEPLAYER 33025
#define ID_CS_REGET                     33026
#define ID_WORLD_RELOADPARTICLEFX       33028
#define ID_VIEWVOB_VOB_SIZEDOWNBBOX     33029
#define ID_VIEWEDIT_TOGGLECAMSPLINES    33032
#define ID_WORLD_ANALYSEWAYNET          33033
#define ID_VIEWVOB_VOB_TEST             33034
#define ID_VOB_TEST                     33034
#define ID_VIEWEDIT_TEXTOUTPUT          33035
#define ID_VIEWEDIT_TOGGLEINFOTEXT      33036
#define ID_VIEW_VOB                     33049
#define ID_VOB_VOBNAME                  33050
#define ID_VOB_VIEWALLPROPERTIES        33052
#define ID_WORLD_CALLSTARTUPSCRIPT      33054
#define ID_VIEWEDIT_TOGGLETOOLS         33055
#define ID_WINDOWS_ALIGNWINDOWSOUTSIDE  33056
#define ID_VOB_CLASS_UP                 33058
#define ID_VOB_CLASS_DN                 33059
#define ID_CUTSCENES_MOVETOBEGIN        33060
#define ID_CUTSCENES_SYNCHRONOUS        33062
#define ID_CUTSCENES_REMOVE             33063
#define ID_VIEWVOB_VOB_MOVEHERE         33064
#define ID_TOGGLE_CAM_POS               33065
#define ID_REMEMBER_CAM_POS             33066
#define ID_WINDOWS_VOBCONTAINER         33069
#define ID_VC_COLLECT                   33070
#define ID_VC_CUSTOM                    33071
#define ID_VIEWVOB_VOB_INSERTTOCONTAINER 33072
#define ID_VOBCONTAINERACTIONS_REMOVEFROMWORLD 33074
#define ID_VOBCONTAINERACTIONS_CLEARVOBLIST 33075
#define ID_VOBCONTAINERACTIONS_SAVEVOBLIST 33076
#define ID_VOBCONTAINERACTIONS_LOADVOBLIST 33077
#define ID_VOBCONTAINERACTIONS_CONVERTTODETAILEDVOB 33078
#define ID_VOBCONTAINERACTIONS_CLEARSELECTED 33080
#define ID_VC_COLLECT10M                33081
#define ID_WORLD_MANIPULATESOUNDS       33082
#define ID_VC_COLLECT100M               33083
#define ID_VC_COLLECT_ILLEGAL           33084
#define ID_VC_VOBTYPES_ALL              33085
#define ID_VC_VOBTYPES_LIGHTS           33086
#define ID_VC_VOBTYPES_WAYPOINTS        33087
#define ID_VC_VOBTYPES_ITEMS            33088
#define ID_VC_VOBTYPES_NPCS             33089
#define ID_VC_VOBTYPES_MOBS             33090
#define ID_VC_VOBTYPES_VOBS             33091
#define ID_VC_VOBTYPES_SOUNDS           33092
#define ID_VC_COLLECT20M                33094
#define ID_VC_COLLECT30M                33095
#define ID_VC_COLLECT_ALL               33096
#define ID_PLAY_GAME                    33097
#define ID_STATUSPANE_COPYVOB           59142
#define ID_STATUSPANE_PICKVOB           59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        278
#define _APS_NEXT_COMMAND_VALUE         33098
#define _APS_NEXT_CONTROL_VALUE         1398
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif

#include "..\zengin\res\zWin32_Version.h"
